//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgjensioniUdhetimit_ProjektiTI2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentAl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentAl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgjensioniUdhetimit_ProjektiTI2.Resources.ContentAl", typeof(ContentAl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto Rezervim te ri.
        /// </summary>
        public static string Add_new_Booking {
            get {
                return ResourceManager.GetString("Add new Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto Klient te ri.
        /// </summary>
        public static string Add_new_Client {
            get {
                return ResourceManager.GetString("Add new Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto Staf te ri.
        /// </summary>
        public static string Add_new_Staff {
            get {
                return ResourceManager.GetString("Add new Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shto Bilete te re.
        /// </summary>
        public static string Add_new_Ticket {
            get {
                return ResourceManager.GetString("Add new Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet Adresa.
        /// </summary>
        public static string Address_is_required {
            get {
                return ResourceManager.GetString("Address is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jeni i sigurt se deshironi ta fshini kete?.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_this_ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datelindja.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet datelindja.
        /// </summary>
        public static string BirthdateRequired {
            get {
                return ResourceManager.GetString("BirthdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervimi.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klientet.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fillimi.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet Data e krijimit.
        /// </summary>
        public static string DateCreated_is_required {
            get {
                return ResourceManager.GetString("DateCreated is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet dita e qendrimit.
        /// </summary>
        public static string DayOfStayingRequired {
            get {
                return ResourceManager.GetString("DayOfStayingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbarimi.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet Koha Mbarimit.
        /// </summary>
        public static string Deadline_is_required {
            get {
                return ResourceManager.GetString("Deadline is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshij.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshij Rezervimin.
        /// </summary>
        public static string Delete_Booking {
            get {
                return ResourceManager.GetString("Delete Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshij Klientin.
        /// </summary>
        public static string Delete_Client {
            get {
                return ResourceManager.GetString("Delete Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshij Stafin.
        /// </summary>
        public static string Delete_Staff {
            get {
                return ResourceManager.GetString("Delete Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fshij Bileten.
        /// </summary>
        public static string Delete_Ticket {
            get {
                return ResourceManager.GetString("Delete Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet data nisjes.
        /// </summary>
        public static string DepartureDateRequired {
            get {
                return ResourceManager.GetString("DepartureDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko Rezervimin.
        /// </summary>
        public static string Edit_Booking {
            get {
                return ResourceManager.GetString("Edit Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko Klientin.
        /// </summary>
        public static string Edit_Client {
            get {
                return ResourceManager.GetString("Edit Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko Stafin.
        /// </summary>
        public static string Edit_Staff {
            get {
                return ResourceManager.GetString("Edit Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiko Bileten.
        /// </summary>
        public static string Edit_Ticket {
            get {
                return ResourceManager.GetString("Edit Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Adresa.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet email adresa.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emri.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet Emri.
        /// </summary>
        public static string FirstName_is_required {
            get {
                return ResourceManager.GetString("FirstName is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjinia.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet Gjinia.
        /// </summary>
        public static string Gender_is_required {
            get {
                return ResourceManager.GetString("Gender is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet nisja prej.
        /// </summary>
        public static string GoingFromRequired {
            get {
                return ResourceManager.GetString("GoingFromRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet nisja ne.
        /// </summary>
        public static string GoingToRequired {
            get {
                return ResourceManager.GetString("GoingToRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet emri hotelit.
        /// </summary>
        public static string HotelNameRequired {
            get {
                return ResourceManager.GetString("HotelNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mbiemri.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet Mbiemri.
        /// </summary>
        public static string LastName_is_required {
            get {
                return ResourceManager.GetString("LastName is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyqu.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Log_off {
            get {
                return ResourceManager.GetString("Log off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet numri personave.
        /// </summary>
        public static string NOPeopleRequired {
            get {
                return ResourceManager.GetString("NOPeopleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet numri i dhomave.
        /// </summary>
        public static string NumberOfRoomsRequired {
            get {
                return ResourceManager.GetString("NumberOfRoomsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri Telefonit.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerkohet NumriTelefonit .
        /// </summary>
        public static string PhoneNumber_is_required {
            get {
                return ResourceManager.GetString("PhoneNumber is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bileta.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
    }
}
